services:

  mysql:
    image: mysql:8.4
    container_name: mysql-sales
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: authdb
      MYSQL_USER: alex
      MYSQL_PASSWORD: 123456

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 10

    networks:
      - sales-network


  redis:
    image: redis:7
    container_name: redis-sales
    restart: always

    ports:
      - "6379:6379"

    networks:
      - sales-network


  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq-sales
    restart: always

    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

    ports:
      - "5672:5672"
      - "15672:15672"

    networks:
      - sales-network


  auth-service:
    image: ceeber/auth-service:latest

    container_name: auth-service
    restart: always

    ports:
      - "8081:8081"

    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}

    depends_on:
      mysql:
        condition: service_healthy

    networks:
      - sales-network


  api-gateway:
    image: ceeber/api-gateway:latest

    container_name: api-gateway
    restart: always

    ports:
      - "8080:8080"

    environment:
      SPRING_PROFILES_ACTIVE: docker

    depends_on:
      auth-service:
        condition: service_started

    networks:
      - sales-network


volumes:

  mysql_data:


networks:

  sales-network:
    driver: bridge